# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "terragrunt-st"
    encrypt = true
    key     = "terragrunt/./terraform.tfstate"
    region  = "us-east-1"
  }
}
