# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "test-backend-circle"
    key            = "dev/ecs_cluster/terraform.tfstate"
    region         = "us-east-1"
  }
}
