name: Chapi Application and Infrastructure Deployment

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write  # Granting id-token permission to the nested workflow
  contents: read
  issues: write

jobs:
  determine_commit_sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine commit SHA
        id: get-sha
        run: |
          pwd
          ls -al
          ls -l ./.github/workflows/
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_HEAD_SHA=$(git rev-parse ${{ github.event.pull_request.head.sha }})
            echo "COMMIT_SHA=$PR_HEAD_SHA" >> $GITHUB_OUTPUT
          else
            MERGE_COMMIT_SHA=$(git rev-parse ${{ github.sha }})
            echo "COMMIT_SHA=$MERGE_COMMIT_SHA" >> $GITHUB_OUTPUT
          fi
    outputs:
      COMMIT_SHA: ${{ steps.get-sha.outputs.COMMIT_SHA }}
  
  prod_app_deploy:
    runs-on: ubuntu-latest
    needs: determine_commit_sha
    if: github.ref == 'refs/heads/main'
    environment: 'prod'
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy App Dev
        uses: ./.github/actions/app-deploy
        with:
          git_project: sgopishetty/terragrunt
          git_ref: ${{ github.ref }}
          commit_id: ${{ needs.determine_commit_sha.outputs.COMMIT_SHA }}
          ecr_repository: flaskappprod