#test1
name: Chapi Application and Infrastructure Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '*'
  push:
    branches:
      - 'develop'
      - 'main'

permissions:
  id-token: write  # Granting id-token permission to the nested workflow
  contents: read

jobs:
  determine_commit_sha:
    runs-on: ubuntu-latest
    steps:
      - name: Determine commit SHA
        id: get-sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            PR_HEAD_SHA=$(git rev-parse ${{ github.event.pull_request.head.sha }})
            echo "::set-output name=COMMIT_SHA=$PR_HEAD_SHA" 
          else
            MERGE_COMMIT_SHA=$(git rev-parse ${{ github.sha }})
            echo "::set-output name=COMMIT_SHA=$MERGE_COMMIT_SHA" 
          fi
    outputs:
      COMMIT_SHA: ${{ steps.get-sha.outputs.COMMIT_SHA }}
  app_deploy:
    needs: determine_commit_sha
    uses: ./.github/workflows/app-deploy.yml
    with:
      git_project: sgopishetty/terragrunt
      git_ref: ${{ github.ref }}
      commit_id: ${{ needs.determine_commit_sha.outputs.COMMIT_SHA }}
  Deploy:
    needs: determine_commit_sha
    uses: ./.github/workflows/terragrunt-deploy.yml
    with:
      git_project: sgopishetty/terragrunt
      git_ref: ${{ github.ref }}
      terragrunt_dir: ./resources/us-east-1/dev
      commit_id: ${{ needs.determine_commit_sha.outputs.COMMIT_SHA }}
      # skip_apply: ${{ !(github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || github.event_name == 'release') }}